import "./globals.css";
import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import Header from "./components/header";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
